apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: <CDSID>-deployment-config
  name: <CDSID>-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: DeploymentConfig
    name: <CDSID>-deployment-config
  maxReplicas: 3
  minReplicas: 1
  cpuUtilization:
    targetCPUUtilizationPercentage: 75