apiVersion: apps/v1
kind: Deployment
metadata:
  name: malyass-deployment
  labels:
    app: malyass-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malyass-deployment
  template:
    metadata:
      labels:
        app: malyass-deployment
    spec:
      # https://docs.openshift.com/container-platform/3.11/admin_guide/scheduling/pod_affinity.html
      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
      # https://medium.com/kokster/scheduling-in-kubernetes-part-2-pod-affinity-c2b217312ae1
      # https://github.com/kubernetes/kubernetes/issues/66992
      # https://kublr.com/blog/implementing-advanced-scheduling-techniques-with-kubernetes/
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - malyass-deployment
            topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - malyass-deployment
              topologyKey: failure-domain.ford.com/zone
      #tolerations:
      ## Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      ## This, along with the annotation above marks this pod as a critical add-on.
      #- key: CriticalAddonsOnly
      #  operator: Exists
      #- key: nvidia.com/gpu
      #  operator: Exists
      #  effect: NoSchedule
      # https://docs.openshift.com/container-platform/3.11/dev_guide/service_accounts.html
      serviceAccountName: default
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: devenablement-workshop-pull-secret
      containers:
      - name: malyass-deployment
        image: registry.ford.com/devenablement/workshop:malyass
        imagePullPolicy: Always        
        ports:
          - name: http
            containerPort: 8080
        env:
        #- name: TLS_CERT
        #  value: /etc/tls/tls.crt
        #- name: TLS_KEY
        #  value: /etc/tls/tls.key
        - name: TCP_PORT
          value: "8080"
        # https://docs.openshift.com/container-platform/3.11/dev_guide/downward_api.html
        # https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        # https://docs.openshift.com/container-platform/3.11/dev_guide/application_memory_sizing.html
        # https://docs.openshift.com/container-platform/3.11/dev_guide/compute_resources.html#dev-compute-resources
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        # https://docs.openshift.com/container-platform/3.11/dev_guide/application_health.html
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          #successThreshold: 1
          #failureThreshold: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
         # successThreshold: 1
          #failureThreshold: 10
          timeoutSeconds: 5