apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: <CDSID>-deployment
    source: caas-workshop
  name: <CDSID>-route
spec:
  host: <CDSID>.app.caas.ford.com
  port:
    targetPort: 8080
  tls:
    termination: edge
    #termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: <CDSID>-service
    weight: 100
  wildcardPolicy: None
